/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedCreateRouteImport } from './routes/_protected.create'
import { Route as OwnerNameRouteImport } from './routes/$owner.$name'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCreateRoute = ProtectedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => ProtectedRoute,
} as any)
const OwnerNameRoute = OwnerNameRouteImport.update({
  id: '/$owner/$name',
  path: '/$owner/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$owner/$name': typeof OwnerNameRoute
  '/create': typeof ProtectedCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$owner/$name': typeof OwnerNameRoute
  '/create': typeof ProtectedCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/$owner/$name': typeof OwnerNameRoute
  '/_protected/create': typeof ProtectedCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$owner/$name' | '/create' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$owner/$name' | '/create' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/$owner/$name'
    | '/_protected/create'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  OwnerNameRoute: typeof OwnerNameRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/create': {
      id: '/_protected/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof ProtectedCreateRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/$owner/$name': {
      id: '/$owner/$name'
      path: '/$owner/$name'
      fullPath: '/$owner/$name'
      preLoaderRoute: typeof OwnerNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedCreateRoute: typeof ProtectedCreateRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedCreateRoute: ProtectedCreateRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  OwnerNameRoute: OwnerNameRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
